FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder
ADD . /go/src/github.com/openshift/egress-router-cni
WORKDIR /go/src/github.com/openshift/egress-router-cni
RUN go build -mod vendor -o bin/egress-router cmd/egress-router/egress-router.go

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9
COPY --from=builder /go/src/github.com/openshift/egress-router-cni/bin/egress-router /usr/src/egress-router-cni/bin/egress-router
LABEL io.k8s.display-name="Egress Router CNI" \
      io.k8s.description="CNI Plugin for Egress Router" \
      io.openshift.tags="openshift"
